### ISSUE TITLE
Errors generated when attempting to run the simulation more than once after opening

### ISSUE THREAD

**Issue by joshuad31** [joshuad31/TandaPay-Simulation#1]
After the simulation is run once the simulation must be shut down and reopened to perform another run.  If this does not happen then the simulation generates multiple checksum failures and other errors.
Please see the attached text file: errors in simulation when attempting double run.txt

It should be possible to run the simulation multiple times without needing to close the simulation each time and then reopen it. This would require the user and system database to be cleared via command by the user.  See the attached image.  Perhaps we can put a button to wipe the databases somewhere here:

![2021-02-15 14_16_11-New Issue · joshuad31_TandaPay-Simulation](https://user-images.githubusercontent.com/5976059/107989767-9296ca80-6f98-11eb-9abf-9bcd2f51253f.png)

[errors in simulation when attempting double run.txt](https://github.com/joshuad31/TandaPay-Simulation/files/5983904/errors.in.simulation.when.attempting.double.run.txt)

**Comment by JamesonWelch** [comment]
In the program here: https://github.com/joshuad31/TandaPay-Simulation/blob/master/Tandapay.py the code that resets the simulation databases starts on line 58 so that it begins with a fresh sheet and at line 98 the same thing for the iterative version of the simulation. This can be used in the UI too. Currently, the simulation needs those files in there because the inherited code base relied on a specific pre-set spreadsheet layout. It didn't make sense to change that up since the database spreadsheets can be copied with a unique name for each run.

**Comment by joshuad31** [comment]
@openedhardware any updates on this?
